// This file is auto-generated by @hey-api/openapi-ts

export type AnsPdfFolderPublic = {
    name: string;
    id: string;
    collection_id: string;
};

export type AnsPdfFoldersPublic = {
    data: Array<AnsPdfFolderPublic>;
    count: number;
};

export type AnsPdfPublic = {
    name: string;
    id: string;
    ans_pdf_folder_id: string;
    filepath: string;
    folder_path: string;
};

export type AnsPdfsPublic = {
    data: Array<AnsPdfPublic>;
    count: number;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_upload_create_ans_pdf_folder = {
    collection_id: string;
};

export type Body_upload_upload_ans_pdf = {
    file: (Blob | File);
    ans_pdf_folder_id: string;
};

export type Body_upload_upload_ans_pdf_to_collection = {
    file: (Blob | File);
    collection_id: string;
};

export type Body_upload_upload_qppdf = {
    file: (Blob | File);
    collection_id: string;
};

export type CollectionCreate = {
    name: string;
    branch?: (string | null);
    department?: (string | null);
    school?: (string | null);
    is_evaluated?: boolean;
};

export type CollectionPublic = {
    name: string;
    branch?: (string | null);
    department?: (string | null);
    school?: (string | null);
    is_evaluated?: boolean;
    id: string;
    user_id: string;
};

export type CollectionsPublic = {
    data: Array<CollectionPublic>;
    count: number;
};

export type CollectionUpdate = {
    name?: (string | null);
    branch?: (string | null);
    department?: (string | null);
    school?: (string | null);
    is_evaluated?: (boolean | null);
};

export type EvaluationPublic = {
    question_no?: (string | null);
    obtained_marks: number;
    max_marks: number;
    feedback: string;
    evaluation_json_path?: (string | null);
    id: string;
    page_id: string;
};

export type EvaluationsPublic = {
    data: Array<EvaluationPublic>;
    count: number;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type QpPdfPublic = {
    name: string;
    filepath: string;
    folder_path: string;
    json_path?: (string | null);
    id: string;
    collection_id: string;
};

export type QpPdfsPublic = {
    data: Array<QpPdfPublic>;
    count: number;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type CollectionsReadCollectionsData = {
    limit?: number;
    skip?: number;
};

export type CollectionsReadCollectionsResponse = (CollectionsPublic);

export type CollectionsCreateCollectionData = {
    requestBody: CollectionCreate;
};

export type CollectionsCreateCollectionResponse = (CollectionPublic);

export type CollectionsReadCollectionData = {
    id: string;
};

export type CollectionsReadCollectionResponse = (CollectionPublic);

export type CollectionsUpdateCollectionData = {
    id: string;
    requestBody: CollectionUpdate;
};

export type CollectionsUpdateCollectionResponse = (CollectionPublic);

export type CollectionsDeleteCollectionData = {
    id: string;
};

export type CollectionsDeleteCollectionResponse = (Message);

export type DownloadDownloadAnsPdfData = {
    ansPdfId: string;
};

export type DownloadDownloadAnsPdfResponse = (unknown);

export type DownloadDownloadQppdfByCollectionData = {
    collectionId: string;
};

export type DownloadDownloadQppdfByCollectionResponse = (unknown);

export type EvaluateEvaluateAnswersheetData = {
    collectionId: string;
};

export type EvaluateEvaluateAnswersheetResponse = ({
    [key: string]: unknown;
});

export type EvaluationsReadEvaluationsByCollectionData = {
    collectionId: string;
    limit?: number;
    skip?: number;
};

export type EvaluationsReadEvaluationsByCollectionResponse = (EvaluationsPublic);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UploadCreateAnsPdfFolderData = {
    formData: Body_upload_create_ans_pdf_folder;
};

export type UploadCreateAnsPdfFolderResponse = (AnsPdfFolderPublic);

export type UploadReadAnsPdfFoldersData = {
    limit?: number;
    skip?: number;
};

export type UploadReadAnsPdfFoldersResponse = (AnsPdfFoldersPublic);

export type UploadUploadAnsPdfData = {
    formData: Body_upload_upload_ans_pdf;
};

export type UploadUploadAnsPdfResponse = (AnsPdfPublic);

export type UploadReadAnsPdfsData = {
    limit?: number;
    skip?: number;
};

export type UploadReadAnsPdfsResponse = (AnsPdfsPublic);

export type UploadUploadAnsPdfToCollectionData = {
    formData: Body_upload_upload_ans_pdf_to_collection;
};

export type UploadUploadAnsPdfToCollectionResponse = (AnsPdfPublic);

export type UploadUploadQppdfData = {
    formData: Body_upload_upload_qppdf;
};

export type UploadUploadQppdfResponse = (QpPdfPublic);

export type UploadReadAnsPdfFolderData = {
    id: string;
};

export type UploadReadAnsPdfFolderResponse = (AnsPdfFolderPublic);

export type UploadReadAnsPdfData = {
    id: string;
};

export type UploadReadAnsPdfResponse = (AnsPdfPublic);

export type UploadGetAnsPdfsByCollectionData = {
    collectionId: string;
    limit?: number;
    skip?: number;
};

export type UploadGetAnsPdfsByCollectionResponse = (AnsPdfsPublic);

export type UploadReadQppdfsData = {
    limit?: number;
    skip?: number;
};

export type UploadReadQppdfsResponse = (QpPdfsPublic);

export type UploadReadQppdfData = {
    id: string;
};

export type UploadReadQppdfResponse = (QpPdfPublic);

export type UploadGetQppdfsByCollectionData = {
    collectionId: string;
    limit?: number;
    skip?: number;
};

export type UploadGetQppdfsByCollectionResponse = (QpPdfsPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);