"""Added filepath and folderpath to AnsPdf

Revision ID: 0d753a186147
Revises: d8b6df8f0212
Create Date: 2025-08-26 08:48:20.817211

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0d753a186147'
down_revision = 'd8b6df8f0212'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anspdf', sa.Column('filepath', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('anspdf', sa.Column('folder_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('anspdf', 'folder_path')
    op.drop_column('anspdf', 'filepath')
    # ### end Alembic commands ###
