"""Add created_at to QpPdf

Revision ID: 1399e7761542
Revises: f5d4ddc836c5
Create Date: 2025-08-27 17:44:53.835634

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1399e7761542'
down_revision = 'f5d4ddc836c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qppdf', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qppdf', 'created_at')
    # ### end Alembic commands ###
