"""add is_evaluated column to anspdf

Revision ID: 8beac075461f
Revises: 64e93d7ceffb
Create Date: 2025-09-15 04:02:22.052033

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8beac075461f'
down_revision = '64e93d7ceffb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anspdf', sa.Column('uploaded_at', sa.DateTime(), nullable=True))
    op.add_column('anspdf', sa.Column('is_evaluated', sa.Boolean(), nullable=True))

    op.execute("UPDATE anspdf SET uploaded_at = NOW() WHERE uploaded_at IS NULL")
    op.execute("UPDATE anspdf SET is_evaluated = FALSE WHERE is_evaluated IS NULL")
    op.alter_column("anspdf", "uploaded_at", nullable=False)
    op.alter_column("anspdf", "is_evaluated", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('anspdf', 'is_evaluated')
    op.drop_column('anspdf', 'uploaded_at')
    # ### end Alembic commands ###
