"""Add folder_path to QpPdf model

Revision ID: d8b6df8f0212
Revises: 9d8026439c13
Create Date: 2025-08-24 23:08:52.583842

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd8b6df8f0212'
down_revision = '9d8026439c13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qppdf', sa.Column('folder_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qppdf', 'folder_path')
    # ### end Alembic commands ###
