"""added json path attr in qppdfs base

Revision ID: f4b155e7100b
Revises: 0d753a186147
Create Date: 2025-08-27 09:28:26.890554

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f4b155e7100b'
down_revision = '0d753a186147'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qppdf', sa.Column('json_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qppdf', 'json_path')
    # ### end Alembic commands ###
